 
image camping_ground_bg = "GFX/background/camping_ground_bg.webp" 
image church_bg = "GFX/background/church_bg.webp" 
image claire_house_bg = "GFX/background/claire_house_bg.webp"
image cphpd_bg = "GFX/background/cphpd_bg.webp"
image daniel_apartment_bg = "GFX/background/daniel_apartment_bg.webp"
image edgar_diner_bg = "GFX/background/edgar_diner_bg.webp"
image forest_bg = "GFX/background/forest_bg.webp"
image gas_station_bg = "GFX/background/gas_station_bg.webp"
image gia_mansion_bg = "GFX/background/gia_mansion_bg.webp"
image gia_ranch_bg = "GFX/background/gia_ranch_bg.webp"
image gia_stable_bg = "GFX/background/gia_stable_bg.webp"
image horse_track_bg = "GFX/background/horse_track_bg.webp"
image library_bg = "GFX/background/library_bg.webp"
image val_apartment_bg = "GFX/background/val_apartment_bg.webp"

image thumbnail_room_val_apartment_bg = "GFX/interface/thumbnail_val_apartment_bg.webp"
image thumbnail_room_camping_ground_bg = "GFX/interface/thumbnail_camping_ground_bg.webp"
image thumbnail_room_church_bg = "GFX/interface/thumbnail_church_bg.webp"
image thumbnail_room_claire_house_bg = "GFX/interface/thumbnail_claire_house_bg.webp"
image thumbnail_room_cphpd_bg = "GFX/interface/thumbnail_cphpd_bg.webp"
image thumbnail_room_daniel_apartment_bg = "GFX/interface/thumbnail_daniel_apartment_bg.webp"
image thumbnail_room_edgar_diner_bg = "GFX/interface/thumbnail_edgar_diner_bg.webp"
image thumbnail_room_forest_bg = "GFX/interface/thumbnail_forest_bg.webp"
image thumbnail_room_gas_station_bg = "GFX/interface/thumbnail_gas_station_bg.webp"
image thumbnail_room_generic = "GFX/interface/thumbnail_generic.webp"
image thumbnail_room_gia_mansion_bg = "GFX/interface/thumbnail_gia_mansion_bg.webp"
image thumbnail_room_gia_ranch_bg = "GFX/interface/thumbnail_gia_ranch_bg.webp"
image thumbnail_room_gia_stable_bg = "GFX/interface/thumbnail_gia_stable_bg.webp"
image thumbnail_room_horse_track_bg = "GFX/interface/thumbnail_horse_track_bg.webp"
image thumbnail_room_library_bg = "GFX/interface/thumbnail_library_bg.webp"
image thumbnail_room_mr_chao_store = "GFX/interface/thumbnail_mr_chao_store.webp"

image burgar = "GFX/burgar.webp"
image fries = "GFX/fries.webp"
image coke = "GFX/coke.webp"